### ISSUE TITLE
Re-use rules

### ISSUE THREAD

**Issue by marroq** [mayaleng/engine#34]
Actually we have basic rules to translate short sentences, possesive nouns, verbs, activities, numbers, and the most are composed by 1, 2 or 3 words each sentence, to construct a larger rule we need to use these short rules, we don't have an article with noun and a verb and to make this rule we have to copy the rule for a verb, the rule for a noun and articles and some rules, like the rule for verbs, are too large and copy and paste all this text every time we can use a verb it isn't the best.

We need to create a new feature to re-use those rules instead of copy all the same rule every time we can apply it.

If we have the rule for verbs and nouns separately, and we need a new rule that include both, we have to copy and paste the text;
 
`
   ...
   {
            "type":"literal",
            "value":template_nouns.
   },
   {
            "type":"literal",
            "value":template_verbs.
   }
`

The idea is re-use the rule using the ID of that rule, instead of create the last rule and copy the text again, we can use the ID and the type will be "defined":

`
   ...
   {
            "type":"defined",
            "value":id_nouns.
   },
   {
            "type":"defined",
            "value":id_verbs.
   }
`

In that space in the rule we search and apply the rule with that ID.

To analyze this, we have to consider:

- The `.Lemma` or `.Translation` and any other property to use, because in the original sentence, the word could be the number 4, but in the re-use rule, the template is written with the word number 1.
- The `details` with the amount of words to use, we have to consider if the rule has 3 words, in the original sentence is going to take 3 words and the next word to use is the number 4 if the last started in the word number 1.

If it is necessary, add more properties to indicate that.

**Comment by marroq** [comment]
@baquiax, can you give me your comments about this?

**Comment by baquiax** [comment]
Thanks, 

You mean a new rules that contain other rules, right? Could you add a simple example to have more visibility.

Anyway, I think what you suggests sounds good to me. I only want to undesrtand the use case. :D

**Comment by marroq** [comment]
Yes, that is the idea, to create a rule not only with other existing rules. A rule with their own template as a normal rule but using an existing rule or as you say, a rule only with other existing rules, an example would be:

We have the rule for VERB:

***(él/ella) corta***

```
{
    "source_language" : "espaol",
    "target_language" : "kaqchikel",
    "pattern" : "VERB",
    "details" : [
        {
            "tag" : "VERB",
            "type" : "M"
        }
    ],
    "output" : [ 
        {
            "type":"literal",
            "value":"{{ if (eq .Word1.Properties.tense \"S\" ) }}x{{ else if (eq .Word1.Properties.tense \"P\")}}y{{ else if (eq .Word1.Properties.tense \"F\")}}xk{{ else if (eq .Word1.Properties.tense \"0\")}}tajin{{end}}"
        },
        {
            "type":"literal",
            "value":"{{ if and ( .Word1.Properties.tr ) (eq .Word..."
        },
        {
            "type":"literal",
            "value":"{{ .Word1.Translation }}"
        }
    ]
}
```

And the rule for proper nouns:

***mi cuchillo***
```
{
    "source_language" : "espaol",
    "target_language" : "kaqchikel",
    "pattern" : "DET,NOUN",
    "details" : [ 
        {
            "tag" : "DET",
            "type" : "P"
        },
        {
            "tag" : "NOUN",
            "type" : "C"
        }
    ],
    "output" : [
        {
            "type":"literal",
            "value":"{{ if and (eq .Word1.Properties.person \"1\") (eq .Word1.Properties.number \"S\") ..."
        },
        {
            "type":"literal",
            "value":"{{ .Word2.Translation }}"
        }
    ]
}
```

And you need a rule for the sentence:

***mi cuchillo corta***

Instead of create a rule with all that last templates again, the rule will look similar like this:

```
{
    "source_language" : "espaol",
    "target_language" : "kaqchikel",
    "pattern" : "DET,NOUN,VERB",
    "details" : [ 
        {
            "tag" : "DET",
            "type" : "P"
        },
        {
            "tag" : "NOUN",
            "type" : "C"
        },
        {
            "tag" : "VERB",
            "type" : "M"
        }
    ],
    "output" : [
        {
            "type":"defined",
            "value":"(id_verb_rule)_507f1f77bcf86cd799439011"
        },
        {
            "type":"defined",
            "value":"(id_proper_nouns_rule)_506d1f77bcf86cd712369dij"
        }
    ]
}
```

And could be have new properties or new tags depending of the necessities during the design or coding.

**Comment by baquiax** [comment]
Looks good to me!

But, do we need to do this to have a MVP?

**Comment by marroq** [comment]
Yes, we need to have this option in the web interface to select the ID of the rule.

Let me know if that was your doubt or I am wrong.
